- name: composer
  src: geerlingguy.composer
  version: 1.7.6

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.4

- name: logrotate
  src: nickhammond.logrotate
  version: v0.0.5

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.22

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.4

- src: TypistTech.trellis-cloudflare-origin-ca
  version: 0.6.0

- src: https://github.com/ItinerisLtd/trellis-cve-2018-6389
  version: 0.1.0
